### ISSUE TITLE
script org_inventory_deploy.py not working

### ISSUE THREAD

**Issue by R1ckkaY** [tmunzer/Mist_library#16]
when executing script org_inventory_deploy.py i get the following error:

```
Traceback (most recent call last):
  File "org_inventory_deploy.py", line 943, in <module>
    start(
TypeError: start() got an unexpected keyword argument 'org_name'

```
could you help with this?
I reinstalled Python and updated the mistapi pip package to no avail.

**Comment by tmunzer** [comment]
Hi,

It should be fixed, can you give it a try?
There was an error in the function parameter name.

**Comment by R1ckkaY** [comment]
Hi,

Yes it works like a charm now, thanks for fixing!
