### ISSUE TITLE
NoneType Error

### ISSUE THREAD

**Issue by hob-o-mat** [tmunzer/Mist_library#21]
Hi Thomas!

Thanks for the great script lib. Sadly, I'm having an issue with the orgs/clone_template.py script. When I try to clone a WLAN template from one org to another, it gives me the "NoneType" error below. 

```
Type of template to clone
0) WLAN Template
1) SWITCH Template
2) WAN Template
3) HUB Profile
Which type of template do you want to clone (0-3)? 0

Available templates:
Traceback (most recent call last):
  File "/Users/[…]/scripts/orgs/clone_template.py", line 800, in <module>
    start(
  File "/Users/[…]/scripts/orgs/clone_template.py", line 600, in start
    template_id = _select_template_to_clone(src_apisession, src_org_id, template_type)
  File "/Users/[…]/scripts/orgs/clone_template.py", line 560, in _select_template_to_clone
    for i, template in enumerate(templates):
TypeError: 'NoneType' object is not iterable

``` 

Actually, there are templates in the org and I read that a possible cause is the different typing of "noneType" in Python 2 and Python 3.

**Comment by tmunzer** [comment]
Hi @hob-o-mat ,

I just fixed the issue. However, the cloning of WLAN Templates is not yet implemented... I'll try to add it in the script this week or next week.

**Comment by hob-o-mat** [comment]
The fix works. I'm looking forward to the implementation. Thanks a lot in advance!

**Comment by tmunzer** [comment]
Cool. I just updated the script to support WLAN Templates.
It will clone
- the wlan template
- the wlans linked to the wlan template
- the wxrule (policies) from the wlan template
- the wxtags (labels) used in the wxrules. It won't create it if a wxtag with the same name already exists in the destination org

**Comment by hob-o-mat** [comment]
Whoo, thank you very much! Works like a charm! I owe you a beer ;-)

**Comment by tmunzer** [comment]
Thanks for the confirmation! :)
