### ISSUE TITLE
org_conf_deploy Error

### ISSUE THREAD

**Issue by peterbrischetto** [tmunzer/Mist_library#22]
I'm getting the following critical error when trying to restore a backup taken with the org_complete_backup script.

See below the output / error.

```
---------------------------- Source Backup/Template ----------------------------

No Template/Backup found for organization None. Please select a folder in the following list.
Available Templates/Backups:
0) Company Name 01
1) Company Name 02

Loading template/backup file org_conf_file.json  ............................. ✔
Analyzing template/backup file org_conf_file.json  ........................... ✖
                                                                                

[CRITICAL ] Unable to parse the template/backup file
```

Looking at the script.log file, this is the last 3 lines

DEBUG:__main__:conf_deploy:_start_deploy_org
INFO:__main__:Loading template/backup file org_conf_file.json : Success
ERROR:__main__:Analyzing template/backup file org_conf_file.json : Failure

Any ideas what could be causing the Critical error?

**Comment by rikardh** [comment]
I'm seeing the same issue.

**Comment by tmunzer** [comment]
Hi,

sorry for the late reply, I will not have the time to work on it before next week.
@rikardh , can you send me your backup by email?

Thanks

**Comment by rikardh** [comment]
Did you get them, @tmunzer?

Cheers!

**Comment by tmunzer** [comment]
Hi @rikardh, yes, I'll take a look at them ASAP

**Comment by tmunzer** [comment]
Hi @peterbrischetto , @rikardh ,

I just updated the script to deploy the backup. It should be better now.
Can you give it a try and let me know?

Thanks

**Comment by peterbrischetto** [comment]
Hi @tmunzer ,

Just tested backing up and restoring an Organization from Global 01 to APAC 01 and it worked perfectly.

Thank you for promptly resolving the issue.
