### ISSUE TITLE
Does the mistapi support proxy environment login

### ISSUE THREAD

**Issue by Sam169-lab** [tmunzer/Mist_library#23]
Hi,

Could help add an example with the proxy environment login at “Environment Variables” section. Tks

**Comment by tmunzer** [comment]
Hi @Sam169-lab ,

I just published 0.52.0 (and 0.52.1) which is adding support for proxy (it was not supported in previous versions).
Proxy configuration can be set in the env file or in the APISession parameters.

Let me know if it works for your.

**Comment by Sam169-lab** [comment]
Hi Tmunzer,

Tks for your help quickly updated the new release and we have been tested that version 0.52.2 was working normal on proxy environments.

Tks

**Comment by Sam169-lab** [comment]
Closed
