### ISSUE TITLE
org_inventory_backup.py doesn't backup switches and gateways

### ISSUE THREAD

**Issue by ikus060** [tmunzer/Mist_library#8]
When I try to execute the org_inventory_backup, I'm expecting to get the full list of inventory. That should include the devices (ap), the switches and the gateways.

Current implement seams to only backup the devices (ap) without any listing of the switch and gateway.

**Comment by tmunzer** [comment]
Hi Patrik,

I'll add the switches and gateways this week.

**Comment by ikus060** [comment]
ok great, can't wait to test it.

**Comment by tmunzer** [comment]
Hi Patrik,

Can you give it a try, I updated the library.

Thanks
